### PR TITLE
csv view of Markdown table

### PR DESCRIPTION
**Pull request by codetojoy**
Assuming the module list grows in size, a CSV view of the data may be useful (esp. given GitHub's filter feature for CSVs). This PR contains a Groovy/Gradle application that generates `~/csv/modules.csv` from the main `README.md`.

A clear downside is that it will need to be generated periodically (ideally with each change). If that is a deal-breaker, no problem. I understand.

### CODE REVIEW

**Comment by jodastephen** [comment]
Merged. We'll see how it works out in practice. Thanks

**Comment by aalmiray** [comment]
Perhaps the script could be run on every merge if a CI build is configured, such as Travis-CI for example 😏

**Comment by jodastephen** [comment]
It could, but that would require a bit of effort setting it up, as it would need to checkin to git (thus needing credentials)

**Comment by aalmiray** [comment]
yes, but Travis already supports that by means of a secure token. Ive' got a similar script running on the Griffon build, see https://github.com/griffon/griffon/blob/development/.travis.yml; it triggers the `update-gh-pages.sh` script when the build is done.

**Comment by codetojoy** [comment]
Quick note that Travis CI idea (or even just a pre-commit hook) is interesting to me, but I'm mostly offline/AFK due to a personal situation, so can't offer much in short-term. Apologies.

**Pull request merged**
