### PR TITLE
Updates for Ikonli 2.1.0

### PR DESCRIPTION
**Pull request by aalmiray**
* Bumped version to 2.1.0
* Added 4 new modules: Dashicons, FontAwesome5, LigatureSymbols, Mapicons.

### CODE REVIEW

**Comment by jodastephen** [comment]
The version is intended to be the earliest version that supported modules.

**Comment by aalmiray** [comment]
Alright. However there are 4 new artifacts. Should I update the PR stating version `2.0.1` for the previously existing modules, and version `2.1.0` for the 4 new ones?

**Comment by jodastephen** [comment]
Yep

**Comment by aalmiray** [comment]
Deal 😄

**Pull request merged**
